// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4);
}

export function AddTasks(arg1) {
  return window['go']['main']['App']['AddTasks'](arg1);
}

export function ApplyCloseAction(arg1, arg2) {
  return window['go']['main']['App']['ApplyCloseAction'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function OpenFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenFolder'](arg1, arg2);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveTask(arg1, arg2) {
  return window['go']['main']['App']['RemoveTask'](arg1, arg2);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
